DEFAULT_SPHERE1_RADIUS = 1.0
DEFAULT_SPHERE1_SECTORS = 36
DEFAULT_SPHERE1_STACKS = 18

DEFAULT_SPHERE2_RADIUS = 1.0
DEFAULT_SPHERE2_SEGMENTS = 10

DEFAULT_SPHERE3_RADIUS = 1.0
DEFAULT_SPHERE3_SUBDIVISIONS = 3