from .arrow_config import *
from .circle_config import *
from .rectangle_config import *
from .star_config import *
from .trapezium_config import *
from .triangle_config import *
from .hexagon_config import *
from .pentagon_config import *
from .elip_config import *